POST http://127.0.0.1:8000/register/ 
Content-Type: application/json

{ "username": "Amir8", "password": "Pass1234!", "email": "amir@mail.com" }

###

POST http://127.0.0.1:8000/login/ 
Content-Type: application/json

{ "username": "Amir8", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token/ 
Content-Type: application/json
Authorization: Token 1cb035ead83f58cb87e67bb5091eddade0c1fe00


